

export const TermsData = [
    {
        title: '1. Information accuracy',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia ea error vero deserunt tenetur, a eius, soluta eveniet nihil illum mollitia doloribus eaque veniam velit eos ipsam animi et?',
        text2: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti quasi harum eius provident tenetur. Aperiam, quod saepe dignissimos, et voluptas, error eius explicabo quasi earum at velit optio totam inventore sit similique placeat quae facere vel voluptatum mollitia sed quo officia fugit? Praesentium voluptatum maiores voluptate dolorum! Perspiciatis, officia a. Ratione magnam praesentium sit harum repellat fuga earum eum tempore.',
        text3: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia ea error vero deserunt tenetur, a eius, soluta eveniet nihil illum mollitia doloribus eaque veniam velit eos ipsam animi et?',
    },
    {
        title: '2.Terms of sale ',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia ea error vero deserunt tenetur, a eius, soluta eveniet nihil illum mollitia doloribus eaque veniam velit eos ipsam animi et?',
        text2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quia ea error vero deserunt tenetur, a eius, soluta eveniet nihil illum mollitia doloribus eaque veniam velit eos ipsam animi et?',
        text3: '',
    },
    {
        title: '3.Payment terms ',
        text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Non voluptatibus, ipsam autem earum, veritatis saepe quo pariatur consequuntur porro dolores iure quae ipsum quis necessitatibus cupiditate perspiciatis excepturi, facere quibusdam sed delectus tenetur omnis? Illum, molestiae! Quam quasi magni omnis animi voluptatem reprehenderit, ut odio dolorem, distinctio impedit dolore beatae ipsum? Fuga veniam, quisquam minus sequi possimus quo quaerat blanditiis debitis suscipit aut sunt corporis quasi facilis eligendi alias sit.',
        text2: 'The payment terms section of your site should include:',
        text3: 'The payment methods you accept Visa, Mastercard etc, Missed/late payment conditions How you will handle refunds/returns, How you will handle payment disputes',
    },
    {
        title: '4. Intellectual property',
        text: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Asperiores labore hic, sunt laudantium incidunt sequi sed recusandae consequuntur enim. Doloremque eum libero ad quaerat! Fugit minima deserunt iure necessitatibus soluta reprehenderit amet ab, molestiae officiis vitae inventore, repellat unde asperiores quod iusto facilis! Odio molestiae distinctio autem maxime, ipsa reprehenderit iusto accusantium esse illum dolorum accusamus minus neque facere repellendus quibusdam debitis. Dignissimos aliquid quas quae sint soluta fuga harum velit error, explicabo animi deleniti sunt nesciunt porro, quasi optio dolorum debitis tenetur totam voluptatem assumenda doloribus id. Quas adipisci suscipit in, a error illum vel quo ratione iure laborum.',
        text2: ' Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse praesentium repudiandae, nisi laborum, natus porro hic iste fugiat amet vero ducimus inventore sapiente. Mollitia voluptatem dolor dolorem ad incidunt quas quos eaque odit voluptas voluptates optio sed nesciunt culpa aut inventore blanditiis non error illo, molestias quasi tempora sapiente nisi.',
        text3: '',
    },
    {
        title: '5. Disclaimer of liability',
        text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus quibusdam numquam recusandae ipsam labore voluptates reiciendis quas, corporis, consectetur quia repellat minima fuga nihil quam molestiae illum praesentium similique magnam eligendi asperiores! Vitae aspernatur et fuga voluptates molestiae expedita inventore quia itaque ipsam quam neque quod quo explicabo, iste natus perferendis voluptate eveniet fugit reprehenderit accusamus nam. Placeat recusandae pariatur reprehenderit veritatis vel adipisci repellendus deleniti delectus saepe maiores incidunt sequi ex dignissimos laboriosam optio voluptas dolorum quam illum, impedit labore doloribus numquam? Possimus, illo laudantium? Ducimus, expedita dolorem nisi deleniti placeat commodi repellendus enim maxime delectus error reprehenderit perspiciatis sed officiis? Nam itaque laborum odit. Odio recusandae maxime, quidem perferendis maiores magni ut veniam dolore ullam, quis illum facere quisquam, at exercitationem eos. Sed delectus debitis, voluptatibus aspernatur accusamus qui alias quae adipisci, tempora doloribus sunt pariatur illo nostrum quos reprehenderit at laboriosam obcaecati veniam. Nisi quibusdam quos nobis.',
        text2: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus quibusdam numquam recusandae ipsam labore voluptates reiciendis quas, corporis, consectetur quia repellat minima fuga nihil quam molestiae illum praesentium similique magnam eligendi asperiores! Vitae aspernatur et fuga voluptates molestiae expedita inventore quia itaque ipsam quam neque quod quo explicabo, iste natus perferendis voluptate eveniet fugit reprehenderit accusamus nam. Placeat recusandae pariatur reprehenderit veritatis vel adipisci repellendus deleniti delectus saepe maiores incidunt sequi ex dignissimos laboriosam optio voluptas dolorum quam illum, impedit labore doloribus numquam? Possimus, illo laudantium? Ducimus, expedita dolorem nisi deleniti placeat commodi repellendus enim maxime delectus error reprehenderit perspiciatis sed officiis? Nam itaque laborum odit. Odio recusandae maxime, quidem perferendis maiores magni ut veniam dolore ullam, quis illum facere quisquam, at exercitationem eos. Sed delectus debitis, voluptatibus aspernatur accusamus qui alias quae adipisci, tempora doloribus sunt pariatur illo nostrum quos reprehenderit at laboriosam obcaecati veniam. Nisi quibusdam quos nobis.',
        text3: '',

    },
    {
        title: '6. Terms of Use',
        text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus quibusdam numquam recusandae ipsam labore voluptates reiciendis quas, corporis, consectetur quia repellat minima fuga nihil quam molestiae illum praesentium similique magnam eligendi asperiores! Vitae aspernatur et fuga voluptates molestiae expedita inventore quia itaque ipsam quam neque quod quo explicabo, iste natus perferendis voluptate eveniet fugit reprehenderit accusamus nam. Placeat recusandae pariatur reprehenderit veritatis vel adipisci repellendus deleniti delectus saepe maiores incidunt sequi ex dignissimos laboriosam optio voluptas dolorum quam illum, impedit labore doloribus numquam? Possimus, illo laudantium? Ducimus, expedita dolorem nisi deleniti placeat commodi repellendus enim maxime delectus error reprehenderit perspiciatis sed officiis? Nam itaque laborum odit. Odio recusandae maxime, quidem perferendis maiores magni ut veniam dolore ullam, quis illum facere quisquam, at exercitationem eos. Sed delectus debitis, voluptatibus aspernatur accusamus qui alias quae adipisci, tempora doloribus sunt pariatur illo nostrum quos reprehenderit at laboriosam obcaecati veniam. Nisi quibusdam quos nobis.',
        text2: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consectetur vitae, ipsum facilis autem porro eos doloremque impedit obcaecati praesentium ea commodi aspernatur, assumenda deserunt quasi aliquid. Velit voluptatem autem consequatur minima laboriosam nulla laborum ea quam sint. Quam, error assumenda. Facere perspiciatis totam possimus ratione non laborum, doloremque corrupti eligendi, eos eius explicabo iste libero placeat similique cupiditate recusandae sit enim exercitationem voluptatum quod rerum eveniet alias. Ratione eligendi perspiciatis consequuntur eos a saepe eum dolorem atque in, expedita aut, beatae error enim ex sint, voluptatibus aliquam. Porro eaque adipisci culpa vero, molestias rem reiciendis. Doloribus nulla, facilis cumque consequuntur corrupti numquam quos aperiam illum ex, laboriosam quisquam odit assumenda eius exercitationem. Suscipit aut architecto, quae nesciunt distinctio culpa dolorum inventore voluptates sed id obcaecati necessitatibus eaque et mollitia, fugiat beatae. Perspiciatis iusto aspernatur modi odio atque corporis illum sapiente impedit, accusamus tenetur, laboriosam repellendus. Voluptatem repellat architecto nulla corporis? Quas perferendis optio esse, sed fugiat cumque? Vitae, laboriosam adipisci, est deserunt iure eum accusantium quod, hic ad facilis ipsum rem a. Dolore, harum? Optio tenetur perspiciatis amet. Necessitatibus nam magni nisi aut, esse vel at nostrum odit corporis dignissimos tenetur, inventore ipsam recusandae non laboriosam praesentium blanditiis minima rerum.',
        text3: '',
    }

];